name: Docker Image CI-fresh

on: push
jobs:
  push_to_registry:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
      - uses: actions/checkout

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME  }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags,labels) for docker
        id: meta
        uses: docker/metadata-action@v1
        with:
             images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
            context: .
            push: true
            tags: dockerswati/repo-docker-public1:latest
